### ISSUE TITLE
max_fee_per_gas设置报错问题

### ISSUE THREAD

**Issue by luowenyue** [okeyzero/evm_Ink_Rs#2]
max_fee_per_gas设置低了总是报JsonRpcError(JsonRpcError { code: -32000, message: "replacement transaction underpriced", data: None })，设置低于5就报错，但实际上价格很低
max_fee_per_gas设置高了直接用我设置的价格当作Gas Price去打了，同时Transaction Fee也显著提高，损失了几百刀😢
设置成220的消耗如下截图
![image](https://github.com/okeyzero/evm_Ink_Rs/assets/3814299/113f8925-b478-4f9f-9ff2-23db38bf3afe)
正常手动打的消耗如下面截图
![image](https://github.com/okeyzero/evm_Ink_Rs/assets/3814299/b11af456-fc8b-4849-a52b-40996024b027)

请作者答疑解惑为啥会这样，感谢🙏！

**Comment by okeyzero** [comment]
1,rpc 问题
2,你之前打铭文 把钱包打废了  什么意思呢 就是 你打了 100张铭文 (gas 为5)只成功了95 张 剩下5张没达到  ，然后你也不想打了  等你 下次操作钱包的时候 你发起的交易 低于 5 就会提示 你gas 太低了   。所以 等你卡着的交易 执行了 就可以了，最好换新钱包打  打铭文费钱包  可能你打了 10000 个  等到你过了很久再次使用钱包的时候 你的钱包开始自动打铭文了 （当然是你卡着的交易）
