### ISSUE TITLE
能用来打符文吗？

### ISSUE THREAD

**Issue by Tongmengjun** [okeyzero/evm_Ink_Rs#3]
能用来打符文吗？

**Comment by okeyzero** [comment]
可以的 但是 收费的 需要改源码

**Comment by bling666-huang** [comment]
@okeyzero 
![image](https://github.com/okeyzero/evm_Ink_Rs/assets/130919100/4e0568a7-94f2-4d73-9e8d-168772762469)
你说的是这种需要改源码对吗？
